# Header
menu:
  Sākums: /
  Mono tējas: /mono
  Par tējām: /par
  Kur atrast: /atrast
header_text: Latvijas laukos vākta un audzēta zāļu tēja
button_mix: Jauktās tējas
button_mono: Mono tējas
header_image: images/header.jpg

# Favicon
favicon_url: images/D.ico

# Default Image for Posts
default_image: images/replacement.jpg

# Google Analytics Tracking ID
matomo_analytics: //matomo.danga.lv/

# Social Accounts
email_url: mailto:aija.bruna@inbox.lv
twitter_url:
facebook_url:
instagram_url:
linkedin_url:
dribbble_url:
github_url:
googleplus_url:
behance_url:
fivehundredpx_url:
